### ISSUE TITLE
receive-loop is crashing without giving a reason

### ISSUE THREAD

**Issue by Quantisan** [Motiva-AI/clj-sqs-extended#91]
the `{:reason nil}` in the log makes it difficult to diagose. this ticket is to fix that so exception messages on receive error are printed properly.

first integration QA on staging failed. all the `receive-loop` processes are crashing for unknown reason. The handle-queue call start out fine, but this error occur when a message comes in from the queue.

One of the error logs,

```
2020-09-17T02:05:04.606148054Z app[worker.1]: Exception in thread "async-dispatch-8" clojure.lang.ExceptionInfo: receive-loop for queue 'https://sqs.us-west-2.amazonaws.com/<REDACTED>/etl_refresh_for_campaign_reports_dev' failed. {:reason nil}
2020-09-17T02:05:04.606393056Z app[worker.1]: 	at clj_sqs_extended.internal.receive$handle_message_receival_error$raise_error__20681.invoke(receive.clj:84)
2020-09-17T02:05:04.606423656Z app[worker.1]: 	at clj_sqs_extended.internal.receive$handle_message_receival_error.invokeStatic(receive.clj:105)
2020-09-17T02:05:04.606495297Z app[worker.1]: 	at clj_sqs_extended.internal.receive$handle_message_receival_error.invoke(receive.clj:80)
2020-09-17T02:05:04.606516317Z app[worker.1]: 	at clj_sqs_extended.internal.receive$receive_loop$fn__20814$state_machine__14311__auto____20833$fn__20835.invoke(receive.clj:134)
2020-09-17T02:05:04.606558257Z app[worker.1]: 	at clj_sqs_extended.internal.receive$receive_loop$fn__20814$state_machine__14311__auto____20833.invoke(receive.clj:134)
2020-09-17T02:05:04.606609877Z app[worker.1]: 	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
2020-09-17T02:05:04.606755988Z app[worker.1]: 	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
2020-09-17T02:05:04.606815849Z app[worker.1]: 	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
2020-09-17T02:05:04.606840579Z app[worker.1]: 	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
2020-09-17T02:05:04.606849229Z app[worker.1]: 	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__14329.invoke(ioc_macros.clj:991)
2020-09-17T02:05:04.606854759Z app[worker.1]: 	at clojure.core.async.impl.channels.ManyToManyChannel$fn__10522.invoke(channels.clj:135)
2020-09-17T02:05:04.606860099Z app[worker.1]: 	at clojure.lang.AFn.run(AFn.java:22)
2020-09-17T02:05:04.606865159Z app[worker.1]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-09-17T02:05:04.606871079Z app[worker.1]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-09-17T02:05:04.606977150Z app[worker.1]: 	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__10409$fn__10410.invoke(concurrent.clj:29)
2020-09-17T02:05:04.606999610Z app[worker.1]: 	at clojure.lang.AFn.run(AFn.java:22)
2020-09-17T02:05:04.607008120Z app[worker.1]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Quantisan** [comment]
I can reproduce this error by simply sending an empty message to the queue manually on AWS console.

**Comment by Quantisan** [comment]
I used the REPL on the live server and re-def'd `handle-message-receival-error` to print out the whole `error` argument

```
 #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Reflector invokeNoArgInstanceMember "Reflector.java" 426]}]
 :trace
 [[clojure.lang.Reflector invokeNoArgInstanceMember "Reflector.java" 426]
  [clj_sqs_extended.aws.sqs$get_serdes_format_attribute invokeStatic "sqs.clj" 177]
  [clj_sqs_extended.aws.sqs$get_serdes_format_attribute invoke "sqs.clj" 172]
  [clj_sqs_extended.aws.sqs$receive_one_message invokeStatic "sqs.clj" 203]
  [clj_sqs_extended.aws.sqs$receive_one_message invoke "sqs.clj" 197]
  [clj_sqs_extended.aws.sqs$receive_message invokeStatic "sqs.clj" 216]
  [clj_sqs_extended.aws.sqs$receive_message invoke "sqs.clj" 208]
  [clj_sqs_extended.aws.sqs$receive_to_channel$fn__23963$state_machine__16989__auto____23972$fn__23975 invoke "sqs.clj" 225]
  [clj_sqs_extended.aws.sqs$receive_to_channel$fn__23963$state_machine__16989__auto____23972 invoke "sqs.clj" 225]
  [clojure.core.async.impl.ioc_macros$run_state_machine invokeStatic "ioc_macros.clj" 978]
  [clojure.core.async.impl.ioc_macros$run_state_machine invoke "ioc_macros.clj" 977]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invokeStatic "ioc_macros.clj" 982]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invoke "ioc_macros.clj" 980]
  [clj_sqs_extended.aws.sqs$receive_to_channel$fn__23963 invoke "sqs.clj" 225]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 628]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__12365$fn__12366 invoke "concurrent.clj" 29]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 834]]}}
	at clj_sqs_extended.internal.receive$handle_message_receival_error$raise_error__28989.invoke(form-init1705793460373707410.clj:5)
	at clj_sqs_extended.internal.receive$handle_message_receival_error.invokeStatic(form-init1705793460373707410.clj:26)
	at clj_sqs_extended.internal.receive$handle_message_receival_error.invoke(form-init1705793460373707410.clj:1)
	at clj_sqs_extended.internal.receive$receive_loop$fn__24333$state_machine__16989__auto____24352$fn__24354.invoke(receive.clj:134)
	at clj_sqs_extended.internal.receive$receive_loop$fn__24333$state_machine__16989__auto____24352.invoke(receive.clj:134)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__17007.invoke(ioc_macros.clj:991)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__12512.invoke(channels.clj:135)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__12365$fn__12366.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
